name: portfolio main workflow

# controls when the workflow will run
on :
  # triggers the workflow on push
  push:
    branches: [ "main" ]

jobs:
  # this workflow contains a single deploy job
  deploy:
    environment:
      name: github-pages
  
    # the type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # runs a single command using the runners shell
      - name: Deploy my homepage
        id: deployment
        uses: actions/deploy-pages@v1
